travis:
  secure:
    BINSTAR_TOKEN: NcUGRAH+EjHo9IHdtJ2ZPTOytg0OPmv+cLcRYKrcQDEYuCNjevanMiUULXEoj84jR2verYInUjrXhG8RPOP6dKqVkcOgIx4hd7NNnNXkQn4/qSeZBSyiNUS/PwjboScw/7DcqbfSe8U9NwOnSbL10rl88mbxnAHBYegQH2dJAVlm4jooZUmsQJzz49016YI6M05UA98nMZCgZ5Nk/na0Z4lCgyAyNwuQPUlImzEsoVsMrsh2Gkgd77s3aYWGDAbiqQ8f9ilsN/uLLMDMIR14Yn9/fwgfgNMO0AePbaKzJkrVBSL90dbz2UZo93uyMt4alB5+q/c0jN7OfiMvg0Amg/VP9KIr3V5+zc46IWLFBMaKlNsIFmASscJcJhosHLy9dgSMmP95/WlqjJbGZdvcwAfENMVAkhLc8EyvujH3ZvRZBdClAk2Xwn6tGHMBjtwYsGaAv4Zm5Jzv+6K1WtEU202dxQjTtN6XO8SaXsKeAp5gWZHqP0TbtHIvUECiaa7n0kW0w1nH6Fen5I4RVYmbE3oZSPMUBvHsW1RmmDAgFBUDU7FysHZhCCtbtNjEjNIZEghxqmpiXogvrlcXyrld9Q4uxxLC/Ao/qhN5bJq9oHmQdwKYPsb3SuNYr1wJcLYA4NKqn9nAwd+PhBsuNLde9vrBtjYNGC0PAT40Y3cVogI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
